extends@: default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    header.body_classes:
                      markdown: true
                    header.icon:
                      type: iconpicker
                      label: Icon
        content:
          fields:
            header.content:
              type: markdown
              validate:
                type: textarea
              label: Page Content
            header.media_order:
              label: Page Media (first one will be displayed next to your content). Please upload square formats (1:1) for this to display nicely (not required for hero images).
            header.hero_image:
              type: filepicker
              label: Hero Image
              preview_images: true
              description: 'If not specified, this defaults to the first image found in the page''s folder'
            # header.body_image:
            #   type: filepicker
            #   label: Body Image
            #   preview_images: true
            #   description: 'Image for the body text'
            